dist: trusty

sudo: false

language: java

# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

matrix:
  include:
    # Open jdk 8
    - jdk: openjdk8

    # Java 8
    - jdk: oraclejdk8
    
    # Java 9
    - jdk: oraclejdk9

    # Java 9
    - env: JDK='JDK9'
      install: . ./install-jdk.sh -F 9
    
    # Java 10
    - env: JDK='JDK 10'
      install: . ./install-jdk.sh -F 10
    
    # Java 11
    - env: JDK='JDK 11'
      install: . ./install-jdk.sh -F 11

    # Java 12
    - env: JDK='JDK 12'
      install: . ./install-jdk.sh -F 12
script:
  - java -version
  - mvn clean install 
